services:
  db:
    image: postgres:16               
    container_name: omics-finder-postgres
    environment:
      POSTGRES_USER: omics_finder           
      POSTGRES_PASSWORD: omics_finder      
      POSTGRES_DB: omics_finder            
    ports:
      - "5432:5432"                    
    volumes:
      - pgdata:/var/lib/postgresql/data       
      - ./sql:/docker-entrypoint-initdb.d       

volumes:
  pgdata: